routes/web.php
Route::post('/file-upload/profile', 'Admin\TutorController@storeProfileVideo')->name('profile.StoreVideo');
Route::post('/file-upload/{id}', 'Admin\TutorController@storePortFolioVideo')->name('portfolio.StoreVideo');
Route::post('/file-upload/package/{id}', 'Admin\TutorController@storePackageVideo')->name('package.StoreVideo');
Route::post('/file-upload/module/{id}', 'Admin\TutorController@storeModuleVideo')->name('module.StoreVideo');
Route::post('/file-upload/live/{id}', 'Admin\TutorController@storeLiveVideo')->name('live.StoreVideo');
  
Route::get('/', 'Auth\LoginController@showLoginForm')->name('welcome');
Route::get('/login1', 'Auth\LoginController@showLoginForm')->name('welcome');

Auth::routes();

Route::get('/home', 'Admin\AdminController@index')->name('admin.home');
Route::get('/terms-and-conditions', 'CommonController@terms')->name('common.terms');
Route::get('/privacy-policy', 'CommonController@policy')->name('common.policy');
Route::get('/get-batch-by-user', 'CommonController@getBatch')->name('common.getBatch');

//SuperAdmin Routes
Route::get('/admin', 'Admin\AdminController@index')->name('admin.home');
Route::get('/admin/help-desk', 'Admin\AdminController@helpDesk')->name('admin.helpdesk');
Route::resource('/admin/terms',  'Admin\TermsController')->except(['show']);
Route::resource('/admin/policy',  'Admin\PolicyController')->except(['show']);
Route::resource('/admin/user',  'Admin\UserController');

Route::middleware('auth')->group(function () {
Route::resource('/admin/tutor',  'Admin\TutorController');
 
// Route::get('/admin/tutor',  'Admin\TutorController@index')->name('tutor.index');
// Route::get('/admin/tutor/{id}',  'Admin\TutorController@show')->name('tutor.show');
// Route::get('/admin/tutor/create/{showNext}',  'Admin\TutorController@createProfile')->name('admin.tutor.create');
Route::get('/admin/tutor/edit/{id}/{showNext}',  'Admin\TutorController@edit')->name('admin.tutor.edit');
Route::post('/admin/tutor/update/{id}/{showNext}',  'Admin\TutorController@update')->name('admin.tutor.update');
Route::get('/admin/tutor/delete/{id}',  'Admin\TutorController@destroy')->name('admin.tutor.delete');

Route::resource('/admin/sessions',  'Admin\SessionsController')->except(['show']);
Route::resource('/admin/payment',  'Admin\PaymentController')->except(['show']);
//skills and category
Route::resource('/admin/category',  'Admin\CategoryController')->except(['show']); 
Route::get('/admin/category/delete/{id}',  'Admin\CategoryController@delete')->name('category.delete'); 

Route::resource('/admin/skill',  'Admin\SkillController')->except(['show']);
Route::get('/admin/skill/delete/{id}',  'Admin\SkillController@delete')->name('skill.delete');

Route::resource('/admin/banner',  'Admin\BannerController')->except(['show']);
Route::resource('/admin/subcategory',  'Admin\SubCategoryController')->except(['show']);



Route::resource('/admin/region',  'Admin\RegionController')->except(['show']);
Route::get('/admin/region/delete/{id}',  'Admin\RegionController@delete')->name('region.delete');
Route::resource('/admin/country',  'Admin\CountryController')->except(['show']);
Route::get('/admin/country/delete/{id}',  'Admin\CountryController@delete')->name('country.delete');

Route::resource('/admin/grade',  'Admin\GradeController')->except(['show']);
Route::resource('/admin/cmsfield',  'Admin\CmsFieldController')->except(['show']);
Route::get('/admin/get_subcategory',  'Admin\SubCategoryController@getSubCategory')->name('admin.getsubcategory');
Route::get('/admin/get_adminsubcategory',  'Admin\SubCategoryController@getAdminSubCategory')->name('admin.getadminsubcategory');
Route::get('/admin/profile', 'Admin\AdminController@profile')->name('admin.profile');
Route::get('/admin/send', 'Admin\EmailController@send')->name('email.send');
Route::post('/admin/profile/update', 'Admin\AdminController@profileUpdate')->name('admin.profile.update');
Route::resource('/admin/admin-banner',  'Admin\BannerController')->except(['show']);

Route::resource('/admin/generalsetting',  'Admin\GeneralsettingController')->except(['show']);
Route::get('/admin/generalsetting/view-currency',  'Admin\GeneralsettingController@viewCurrency')->name('admin.settings.viewCurrency');
Route::post('/admin/generalsetting/view-currency/store',  'Admin\GeneralsettingController@currencyStore')->name('admin.settings.currencyStore');
Route::post('/admin/generalsetting/view-currency/update',  'Admin\GeneralsettingController@currencyUpdate')->name('admin.settings.currencyUpdate');

Route::get('/admin/generalsetting/view-currency/create',  'Admin\GeneralsettingController@createCurrency')->name('admin.currency_settings.createCurrency');
Route::post('/admin/generalsetting/storeCurrency',  'Admin\GeneralsettingController@storeCurrency')->name('admin.currency_settings.storeCurrency');
Route::get('/admin/generalsetting/view-currency/{id}/edit',  'Admin\GeneralsettingController@editCurrency')->name('admin.currency_settings.editCurrency');
Route::post('/admin/generalsetting/updateCurrency/{id}',  'Admin\GeneralsettingController@updateCurrency')->name('admin.currency_settings.updateCurrency');
Route::get('/admin/generalsetting/deleteCurrency/{id}',  'Admin\GeneralsettingController@deleteCurrency')->name('admin.currency_settings.deleteCurrency');
Route::get('/admin/generalsetting/tier',  'Admin\GeneralsettingController@get_tier')->name('admin.tier.index');
Route::get('/admin/generalsetting/tier/create',  'Admin\GeneralsettingController@createTier')->name('admin.tier.create');
Route::post('/admin/generalsetting/tier',  'Admin\GeneralsettingController@storeTier')->name('admin.tier.storeTier');
Route::get('/admin/generalsetting/tier/{id}/edit', 'Admin\GeneralsettingController@editTier')->name('admin.tier.edit');
Route::post('/admin/generalsetting/tier/update/{id}',  'Admin\GeneralsettingController@updateTier')->name('admin.tier.update');
Route::get('/admin/generalsetting/tier/delete/{id}',  'Admin\GeneralsettingController@deleteTier')->name('admin.tier.delete');
Route::get('/admin/generalsetting/tier/currencyRange',  'Admin\GeneralsettingController@view_currency_range')->name('admin.tier.currency_range.index');
Route::get('/admin/generalsetting/tier/currencyRange/create',  'Admin\GeneralsettingController@createTierCurrency')->name('admin.tier.currency_range.create');
Route::post('/admin/generalsetting/tier/currencyRange/store',  'Admin\GeneralsettingController@StoreTierCurrency')->name('admin.tier.currency_range.store');
Route::get('/admin/generalsetting/tier/currencyRange/{id}/edit',  'Admin\GeneralsettingController@editTierCurrency')->name('admin.tier.currency_range.edit');
Route::post('/admin/generalsetting/tier/currencyRange/update/{id}',  'Admin\GeneralsettingController@updateTierCurrency')->name('admin.tier.currency_range.update');
Route::get('/admin/generalsetting/tier/currencyRange/delete/{id}',  'Admin\GeneralsettingController@deleteTierCurrency')->name('admin.tier.currency_range.delete');


Route::resource('/admin/recentbooking',  'Admin\RecentbookingController')->except(['show']);
Route::get('/get_admin_payment',  'Admin\PaymentController@get_admin_payment')->name('get_admin_payment');
Route::get('/admin/refund-payment/{id}', 'Admin\PaymentController@refundPayment')->name('buddy.refund.payment');
Route::get('/get_admin_recentbooking',  'Admin\RecentbookingController@get_admin_recentbooking')->name('get_admin_recentbooking');

Route::get('/admin/tutor/portfolio/create/{id}/{showNext}', 'Admin\TutorController@createPortfolio')->name('tutor.portfolio.create');
Route::post('/admin/tutor/portfolio/{showNext}', 'Admin\TutorController@storePortfolio')->name('tutor.portfolio.store');
Route::get('/admin/tutor/portfolio/{id}/edit', 'Admin\TutorController@editPortfolio')->name('tutor.portfolio.edit');
Route::post('/admin/tutor/portfolio/update/{id}', 'Admin\TutorController@updatePortfolio')->name('tutor.portfolio.update');
Route::get('/admin/tutor/portfolio/delete/{id}', 'Admin\TutorController@deletePortfolio')->name('tutor.portfolio.delete');

Route::get('/admin/tutor/package/index/{id}', 'Admin\TutorController@viewPackage')->name('tutor.package.view');
Route::get('/admin/tutor/package/view/{id}', 'Admin\TutorController@showPackage')->name('tutor.package.show');
Route::get('/admin/tutor/package/create/{id}/{showNext}', 'Admin\TutorController@createPackage')->name('tutor.package.create');
Route::get('/admin/tutor/package/{id}/edit', 'Admin\TutorController@editPackage')->name('tutor.package.edit');
Route::post('/admin/tutor/package/{showNext}', 'Admin\TutorController@storePackage')->name('tutor.package.store');
Route::post('/admin/tutor/package/update/{id}', 'Admin\TutorController@updatePackage')->name('tutor.package.update');
Route::get('/admin/tutor/package/delete/{id}', 'Admin\TutorController@deletePackage')->name('tutor.package.delete');

Route::get('/admin/tutor/module/view/{id}', 'Admin\TutorController@showModule')->name('tutor.module.show');
Route::get('/admin/tutor/module/index/{id}', 'Admin\TutorController@viewModule')->name('tutor.module.view');
Route::get('/admin/tutor/module/create/{id}/{showNext}', 'Admin\TutorController@createModule')->name('tutor.module.create');
Route::get('/admin/tutor/module/{id}/edit', 'Admin\TutorController@editModule')->name('tutor.module.edit');
Route::post('/admin/tutor/module/{showNext}', 'Admin\TutorController@storeModule')->name('tutor.module.store');
Route::post('/admin/tutor/module/update/{id}', 'Admin\TutorController@updateModule')->name('tutor.module.update');
Route::get('/admin/tutor/module/delete/{id}', 'Admin\TutorController@deleteModule')->name('tutor.module.delete');

Route::get('/admin/tutor/liveclass/view/{id}', 'Admin\TutorController@showLiveClass')->name('tutor.live_class.show');
Route::get('/admin/tutor/liveclass/index/{id}', 'Admin\TutorController@viewLiveClass')->name('tutor.live_class.view');

app/CmsField.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

class CmsField extends Model
{
    use Notifiable;
    protected $fillable = [
        'cms_heading', 'cms_description', 'cms_image', 'display_order', 'button_text'
    ];
}

app/Http/Controllers/Admin/CmsFieldController.php
<?php

namespace App\Http\Controllers\Admin;

use App\CmsField;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CmsFieldController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cmsfields=CmsField::all();
        return view('admin.cmsfield.index',\compact('cmsfields'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.cmsfield.create_edit');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'cms_heading' => ['required', 'string', 'max:255'],
            'cms_description' => ['required', 'string'],
            'display_order' => ['required', 'numeric'],
            'button_text' => ['required','string', 'max:255'],
        ]);

        $file = $request->file('cms_image');
        if($file!="") {
            $path = $file->store('/cms', ['disk' => 'public']);
        }

        $category =  CmsField::create([
            'cms_heading' => $request->cms_heading,
            'cms_description' => $request->cms_description,
            'cms_image' => isset($path)?$path:'',
            'display_order' => $request->display_order,
            'button_text' => $request->button_text,

        ]);
        return redirect()->route('cmsfield.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $cmsfield = CmsField::findOrFail($id);
        return view('admin.cmsfield.create_edit', \compact('cmsfield'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'cms_heading' => ['required', 'string', 'max:255'],
            'cms_description' => ['required', 'string'],
            'display_order' => ['required', 'numeric'],
            'button_text' => ['required','string', 'max:255'],
        ]);

        $file = $request->file('cms_image');
        if($file!="") {
            $path = $file->store('/cms', ['disk' => 'public']);
        }

        $cmsfield =  CmsField::updateOrCreate(
            ['id' =>$id],
            [
                'cms_heading' => $request->cms_heading,
                'cms_description' => $request->cms_description,
                'cms_image' => ($request->hasFile('cms_image')) ? $path : ($request->image_url?$request->image_url:null),
                'display_order' => $request->display_order,
                'button_text' => $request->button_text,
            ]
        );
        return redirect()->route('cmsfield.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $cmsfields = CmsField::find($id);
        $cmsfields->delete();

        return redirect()->route('cmsfield.index');
    }
}

resources/views/admin/cmsfield/create_edit.blade.php
@php
    $formAction = isset($cmsfield) ? route('cmsfield.update', $cmsfield->id) : route('cmsfield.store');
    $issetCmsfield = isset($cmsfield) ? 1 : 0;
@endphp
@extends('layouts.dashboard')

@section('content')
@include('partials.nav')
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header card-header-primary">
            <h4 class="card-title">
              @isset($cmsfield)
                  Edit Cmsfield Details
              @else
                  Add New Cmsfield<Tutor></Tutor>
              @endisset
            </h4>
            {{--<p class="card-cmsfield">Complete your profile</p>--}}
          </div>
          <div class="card-body">
            <form action="{{ $formAction }}" method="POST" accept-charset="UTF-8" enctype="multipart/form-data">
              @isset($cmsfield) @method('PUT') @endisset
              @csrf
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label class="bmd-label-floating">Cmsfield Heading</label>
                    <input id="cms_heading" type="text" name="cms_heading" class="form-control"
                        value="{{ old('cms_heading') ?? ($issetCmsfield ? $cmsfield->cms_heading : '')  }}" required>
                    @error ('cms_heading')
                        <p class="text-danger">{{ $message }}</p>
                    @enderror
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label class="bmd-label-floating">Display Order</label>
                    <input id="display_order" type="number" name="display_order" class="form-control"
                        value="{{ old('display_order') ?? ($issetCmsfield ? $cmsfield->display_order : '')  }}">
                    @error ('display_order')
                        <p class="text-danger">{{ $message }}</p>
                    @enderror
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label class="bmd-label-floating">Button Text</label>
                    <input id="button_text" type="text" name="button_text" class="form-control"
                        value="{{ old('button_text') ?? ($issetCmsfield ? $cmsfield->button_text : '')  }}" required>
                    @error ('button_text')
                        <p class="text-danger">{{ $message }}</p>
                    @enderror
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <label class="bmd-label-floating">Cmsfield Description</label>
                    <textarea class="form-control" id="cms_description" name="cms_description" rows="10" required>{{ old('cms_description') ?? ($issetCmsfield ? $cmsfield->cms_description : '')  }}</textarea>
                    @error ('cms_description')
                    <p class="text-danger">{{ $message }}</p>
                    @enderror
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label class="bmd-label-floating">CMS Image (329x248) : {{isset($cmsfield->cms_image) ? $cmsfield->cms_image : ''}}</label>
                    <input id="cms_image" type="file" name="cms_image" class="form-control"
                           value="{{ old('cms_image') ?? ($issetCmsfield ? $cmsfield->cms_image : '')  }}">
                    <input type="hidden" name="image_url" value="{{isset($cmsfield->cms_image) ? $cmsfield->cms_image : ''}}">
                    @error ('cms_image')
                    <p class="text-danger">{{ $message }}</p>
                    @enderror
                  </div>
                </div>
              </div>
              <button type="submit" class="btn btn-primary pull-right">Submit</button>
              <div class="clearfix"></div>
            </form>
          </div>
        </div>
      </div>
      <!-- <div class="col-md-4">
        <div class="card card-profile">
          <div class="card-avatar">
            <a href="javascript:;">
              <img class="img" src="../assets/img/faces/marc.jpg" />
            </a>
          </div>
          <div class="card-body">
            <h6 class="card-cmsfield text-gray">CEO / Co-Founder</h6>
            <h4 class="card-title">Alec Thompson</h4>
            <p class="card-description">
              Don't be scared of the truth because we need to restart the human foundation in truth And I love you like Kanye loves Kanye I love Rick Owens’ bed design but the back is...
            </p>
            <a href="javascript:;" class="btn btn-primary btn-round">Follow</a>
          </div>
        </div>
      </div> -->
    </div>
    @isset($cmsfield)
    {{--<div class="row">--}}
      {{--<div class="col-md-8">--}}
        {{--<div class="card">--}}
          {{--<div class="card-header card-header-primary">--}}
            {{--<h4 class="card-title">--}}
              {{--Delete this Cmsfield--}}
            {{--</h4>--}}
          {{--</div>--}}
          {{--<div class="card-body">--}}
            {{--<form action="{{ route('cmsfield.destroy', $cmsfield->id) }}" method="POST">--}}
                {{--@csrf--}}
                {{--@method('DELETE')--}}
              {{--<div class="row">--}}
                {{--<div class="col-md-12">--}}
                  {{--Do you really want to do this ? Make sure you are selected the right item. This action is irreversible.--}}
                  {{--All data associated with this item will be erased permanantly.--}}
                {{--</div>--}}
              {{--</div>--}}
              {{--<button type="submit" class="btn btn-primary pull-right">Delete</button>--}}
              {{--<div class="clearfix"></div>--}}
            {{--</form>--}}
          {{--</div>--}}
        {{--</div>--}}
      {{--</div>--}}
    {{--</div>--}}
    @endisset
  </div>
</div>
@endsection

resources/views/admin/cmsfield/index.blade.php
@extends('layouts.dashboard')

@section('content')
@include('partials.nav')
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header card-header-primary">
            <h4 class="card-title ">Cms Fields</h4>
            {{--<ul class="nav nav-tabs" data-tabs="tabs">--}}
              {{--<li class="nav-item">--}}
                {{--<a class="nav-link active" href="{{route('cmsfield.create')}}" >--}}
                  {{--<i class="material-icons">supervisor_account</i> Add Cms Field--}}
                  {{--<div class="ripple-container"></div>--}}
                  {{--<div class="ripple-container"></div></a>--}}
              {{--</li>--}}
            {{--</ul>--}}
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table">
                <thead class=" text-primary">
                  <th>ID</th>
                  <th>Cms Field Heading</th>
                  <th>Display Order</th>
                  <th class="text-right" width="">Action</th>
                </thead>
                <tbody>
                  @isset($cmsfields)
                  @foreach($cmsfields as $cmsfield)
                  <tr>
                    <td>{{$loop->index + 1}}</td>
                    <td>{{$cmsfield->cms_heading}}</td>
                    <td>{{$cmsfield->display_order}}</td>
                    <td class="td-actions" width="5%">
                      <a href="{{ route('cmsfield.edit', $cmsfield->id) }}">
                        <button type="button" rel="tooltip" title="Edit Task" class="btn btn-primary btn-link btn-sm">
                          <i class="material-icons">edit</i>
                        </button>
                      </a>
                    </td>
                  </tr>
                  @endforeach
                  @endisset
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection