v2/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Auth\LoginController@showLoginForm')->name('welcome');

Auth::routes();

Route::get('/home', 'Admin\AdminController@index')->name('admin.home');
Route::get('/terms-and-conditions', 'CommonController@terms')->name('common.terms');
Route::get('/privacy-policy', 'CommonController@policy')->name('common.policy');
Route::get('/get-batch-by-user', 'CommonController@getBatch')->name('common.getBatch');

//SuperAdmin Routes
Route::get('/admin', 'Admin\AdminController@index')->name('admin.home');
Route::get('/admin/help-desk', 'Admin\AdminController@helpDesk')->name('admin.helpdesk');
Route::resource('/admin/terms',  'Admin\TermsController')->except(['show']);
Route::resource('/admin/policy',  'Admin\PolicyController')->except(['show']);
Route::resource('/admin/user',  'Admin\UserController');
Route::resource('/admin/tutor',  'Admin\TutorController');
Route::resource('/admin/sessions',  'Admin\SessionsController')->except(['show']);
Route::resource('/admin/payment',  'Admin\PaymentController')->except(['show']);
Route::resource('/admin/category',  'Admin\CategoryController')->except(['show']);
Route::resource('/admin/banner',  'Admin\BannerController')->except(['show']);
Route::resource('/admin/subcategory',  'Admin\SubCategoryController')->except(['show']);
Route::resource('/admin/skill',  'Admin\SkillController')->except(['show']);
Route::resource('/admin/country',  'Admin\CountryController')->except(['show']);
Route::resource('/admin/grade',  'Admin\GradeController')->except(['show']);
Route::resource('/admin/cmsfield',  'Admin\CmsFieldController')->except(['show']);
Route::get('/admin/get_subcategory',  'Admin\SubCategoryController@getSubCategory')->name('admin.getsubcategory');
Route::get('/admin/get_adminsubcategory',  'Admin\SubCategoryController@getAdminSubCategory')->name('admin.getadminsubcategory');
Route::get('/admin/profile', 'Admin\AdminController@profile')->name('admin.profile');
Route::get('/admin/send', 'Admin\EmailController@send')->name('email.send');
Route::post('/admin/profile/update', 'Admin\AdminController@profileUpdate')->name('admin.profile.update');
Route::resource('/admin/admin-banner',  'Admin\BannerController')->except(['show']);

Route::resource('/admin/generalsetting',  'Admin\GeneralsettingController')->except(['show']);
Route::resource('/admin/recentbooking',  'Admin\RecentbookingController')->except(['show']);
Route::get('/get_admin_payment',  'Admin\PaymentController@get_admin_payment')->name('get_admin_payment');
Route::get('/admin/refund-payment/{id}', 'Admin\PaymentController@refundPayment')->name('buddy.refund.payment');
Route::get('/get_admin_recentbooking',  'Admin\RecentbookingController@get_admin_recentbooking')->name('get_admin_recentbooking');

Route::get('/admin/tutor/portfolio/{id}', 'Admin\TutorController@createPortfolio')->name('tutor.portfolio.create');
Route::post('/admin/tutor/portfolio', 'Admin\TutorController@storePortfolio')->name('tutor.portfolio.store');
Route::post('/admin/tutor/portfolio/update', 'Admin\TutorController@updatePortfolio')->name('tutor.portfolio.update');
Route::get('/admin/tutor/portfolio/delete/{id}', 'Admin\TutorController@deletePortfolio')->name('tutor.portfolio.delete');

Route::get('/admin/tutor/package/{id}', 'Admin\TutorController@createPackage')->name('tutor.package.create');
Route::post('/admin/tutor/package', 'Admin\TutorController@storePackage')->name('tutor.package.store');
Route::post('/admin/tutor/package/update', 'Admin\TutorController@updatePackage')->name('tutor.package.update');
Route::get('/admin/tutor/package/delete/{id}', 'Admin\TutorController@deletePackage')->name('tutor.package.delete');

Route::get('/admin/tutor/batch/{id}', 'Admin\TutorController@createBatch')->name('tutor.batch.create');
Route::post('/admin/tutor/batch', 'Admin\TutorController@storeBatch')->name('tutor.batch.store');
Route::post('/admin/tutor/batch/update', 'Admin\TutorController@updateBatch')->name('tutor.batch.update');
Route::get('/admin/tutor/batch/delete/{id}', 'Admin\TutorController@deleteBatch')->name('tutor.batch.delete');

v2/app/Http/Controllers/Admin/TutorController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Country;
use App\Skill;
use App\SubCategory;
use App\Http\Controllers\Controller;
use App\TutorDetail;
use App\TutorPortfolio;
use App\TutorSession;
use Illuminate\Http\Request;
use App\User;
use App\Package;
use App\PackageBatch;
use App\Batch;
use App\HelpDesk;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;
use Validator;
use App\Traits\VideoFFMpeg;


class TutorController extends Controller
{
  use VideoFFMpeg;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $users = User::where('role','tutor')->get();
        return view('admin.tutor.index',\compact('users'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $subset=Category::all();
        $category = $subset->map(function ($subset) {
            return collect($subset->toArray())
                ->only(['id', 'category_name'])
                ->all();
        });
        $sub_category=array();
        $country_subset=Country::all();
        $countries = $country_subset->map(function ($country_subset) {
            return collect($country_subset->toArray())
                ->only(['id', 'country_name'])
                ->all();
        });
        $skill_subset=Skill::all();
        $skills = $skill_subset->map(function ($skill_subset) {
            return collect($skill_subset->toArray())
                ->only(['id', 'skill_name'])
                ->all();
        });
        return view('admin.tutor.create_edit',\compact('category','sub_category','countries','skills'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'category' => ['required'],
            'dob' => ['required', 'date'],
            // 'sub_category' => ['required'],
//            'slug' => ['required', 'string', 'max:255', 'unique:users'],
//            'phone_number' => ['required', 'numeric', 'digits:10','unique:users'],
            'location' => ['required', 'string',],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
            'profile_image' => ['nullable','mimes:jpg,jpeg,png','max:1024'],
        ]);
        do {
            $token_key = Str::random(24); ///api_token' => Str::random(60),use Illuminate\Support\Str;
        } while (User::where("token", "=", $token_key)->first() instanceof User);

        $path_image = '';
        if($request->profile_image){
            $pro_image = $request->file('profile_image');
            $path_image = $pro_image->store('/uploads/tutor',['disk' => 'public']);
        }

        $user =  User::create([
            'name' => $request->name,
            'slug' => Str::slug($request->slug),
            'dob' => $request->dob,
            'email' => $request->email,
            'phone_number' => $request->phone_number,
            'location' => $request->location,
            'token' => $token_key,
            'role' => 'tutor',
            'password' => Hash::make($request->password),
            'profile_image' => $path_image,
        ]);

        if(isset($request->college_name))
        {
            foreach ($request->college_name as $key=>$value){
                if($value){
                    $experience[$key]=[
                        'name' => $value,
                        'designation' => $request->designation[$key]
                    ];
                }
            }
        }



        $tutor_detail=TutorDetail::create([
            'user_id'=>$user->id,
            'category'=>$request->category,
            'sub_category'=>3,
            'skills'=>1,
            // 'about'=>$request->about,
            // 'experience'=>json_encode($experience),
        ]);



        return redirect()->route('tutor.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::findOrFail($id);
        return view('admin.tutor.show', \compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(int $userId)
    {
        $user = User::findOrFail($userId);
        $subset=Category::all();
        $category = $subset->map(function ($subset) {
            return collect($subset->toArray())
                ->only(['id', 'category_name'])
                ->all();
        });
        $category_object=Category::where('id',$user->tutor_detail->category)->first();
        $sub_category=array();
        if($category_object) {
            $sub_cat = SubCategory::where('category_id', $category_object->id)->get();
            $sub_category = $sub_cat->map(function ($sub_cat) {
                return collect($sub_cat->toArray())
                    ->only(['id', 'sub_category_name'])
                    ->all();
            });
        }
        $country_subset=Country::all();
        $countries = $country_subset->map(function ($country_subset) {
            return collect($country_subset->toArray())
                ->only(['id', 'country_name'])
                ->all();
        });
        $skill_subset=Skill::all();
        $skills = $skill_subset->map(function ($skill_subset) {
            return collect($skill_subset->toArray())
                ->only(['id', 'skill_name'])
                ->all();
        });

        return view('admin.tutor.create_edit', \compact('user','category','sub_category','countries','skills'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'email' => 'required|email|unique:users,email,'.$id,
//            'slug' => 'required|unique:users,slug,'.$id,
//            'phone_number' => 'required|unique:users,phone_number,'.$id,
'category' => ['required'],
'dob' => 'required',
            // 'sub_category' => ['required'],
            'name' => 'required',
            'location' => 'required',
            'password' => 'sometimes|confirmed',
            'profile_image' => ['nullable','mimes:jpg,jpeg,png','max:1024'],
        ]);

        $path_image = '';
        if($request->profile_image){
            if(User::where('id', $id)->exists()){
                $user = User::find($id);
                if($user->profile_image){
                    if(Storage::disk('public')->exists($user->profile_image)){
                        Storage::disk('public')->delete($user->profile_image);
                    }
                }
            }
            $pro_image = $request->file('profile_image');
            $path_image = $pro_image->store('/uploads/tutor',['disk' => 'public']);
        }

        if($request->password)
        {
            $data = [
                'name' => $request->name,
                'email' => $request->email,
                'slug' => Str::slug($request->slug),
                'phone_number' => $request->phone_number,
                'location' => $request->location,
                'password' => Hash::make($request->password),
                'profile_image' => $path_image,
            ];
        }
        else{
            $data = [
                'name' => $request->name,
                'email' => $request->email,
                'slug' => Str::slug($request->slug),
                'phone_number' => $request->phone_number,
                'location' => $request->location,
                'profile_image' => $path_image,
            ];
        }
        if(isset($request->college_name))
        {

        foreach ($request->college_name as $key=>$value){
            if($value){
                $experience[$key]=[
                    'name' => $value,
                    'designation' => $request->designation[$key]
                ];
            }
        }
    }

        $tutor_data = [
            'category'=>$request->category,
            'sub_category'=>1,
            // 'skills'=>$request->skills,
            // 'about'=>$request->about,
            // 'experience'=>json_encode($experience),
        ];

        $user =  User::updateOrCreate(
            ['id' =>$id],
            $data
        );

        $tutor_detail =  TutorDetail::updateOrCreate(
            ['user_id' =>$id],
            $tutor_data
        );

        return redirect()->route('tutor.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);

        $tutor_details = TutorDetail::where('user_id',$id)->get();

        foreach ($tutor_details as $tutor_detail) {
            $tutor_detail->delete();
        }

        $batches = Batch::where('user_id',$id)->get();
        foreach ($batches as $batch) {
            $packageBatch = PackageBatch::where('batch_id',$batch->id)->delete();
            $session = TutorSession::where('batch_id',$batch->id)->delete();
            $batch->delete();
        }

        $packages = Package::where('user_id',$id)->get();
        foreach ($packages as $package) {
            $packageBatch = PackageBatch::where('package_id',$package->id)->delete();
            $package->delete();
        }

v2/resources/views/admin/tutor/create_edit_package.blade.php
@php
    $formAction = route('tutor.package.store', $id);
@endphp
@extends('layouts.dashboard')

@section('content')
@include('partials.nav')
<div class="content">
  <div class="container-fluid">
    <div class="row d-flex justify-content-center">
      <div class="col-lg-8">
        <div class="card">
          <div class="card-header card-header-primary">
            <h4 class="card-title">
                  Guru Packages
            </h4>
            <p class="card-category">Manage guru package</p>
          </div>
          <div class="card-body">
            <form action="{{ $formAction }}" method="POST" accept-charset="UTF-8" enctype="multipart/form-data">
              @csrf
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <input id="user_id" type="hidden" name="user_id" class="form-control" value="{{$id}}">
                    <label class="bmd-label-floating">Package Name</label>
                    <input id="package_name" type="text" name="package_name" class="form-control"
                        value="">
                    @error ('package_name')
                        <p class="text-danger">{{ $message }}</p>
                    @enderror
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label class="bmd-label-floating">Description</label>
                    <input id="description" type="text" name="description" class="form-control"
                    value="">
                    @error('location')
                    <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                  </div>
                </div>
                {{-- <div class="col-md-6">
                  <div class="form-group">
                    <label class="bmd-label-floating">Subscription Fee</label>
                    <input id="subscription_fee" type="number" name="subscription_fee" class="form-control"
                    value="">
                    @error('subscription_fee')
                    <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                  </div>
                </div> --}}

                <div class="col-md-6">
                  <div class="form-group">
                    <label class="bmd-label-floating">Batch</label>
                    
                    <select id="batch_id" name="batch_id[]" multiple class="form-control">
                      @isset($userBatches)
                      @foreach($userBatches as $value)
                      <option value="{{$value->id}}">{{$value->batch_name}}</option>
                      @endforeach
                      @endisset
                    </select>
                    
                    
                    @error('batch_id')
                    <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                  </div><div style="font-size: 12px;">Not required,You can add it, Manage batch is in Guru Actions (Previous Menu).</div>
                </div>
              </div>
              
                  {{-- <div class="row"> --}}
              <button type="submit" class="btn btn-primary pull-right">Submit</button>
              {{-- <div class="clearfix"></div> --}}
                  {{-- </div> --}}
            </form>
            <div class="table-responsive">
              <table class="table">
                <thead class=" text-primary">
                  <th>ID</th>
                  <th>Package Name</th>
                  <th>Description</th>
                  {{-- <th>Subcription fee</th> --}}
                  <th>Batch</th>
                  <th class="text-right">Action</th>
                </thead>
                <tbody>
                  @isset($userPackages)
                  @foreach($userPackages as $userPackage)
                  <tr>
                    <td>{{$loop->index + 1}}</td>
                    <td>{{$userPackage->package_name}}</td>
                    <td>{{$userPackage->description}}</td>
                    {{-- <td>{{$userPackage->subscription_fee}}</td> --}}
                    <td>
                      @isset($userPackage->batches)
                      @foreach($userPackage->batches as $value)
                      {{$value->batch_name}},
                      @endforeach
                      @endisset
                      
                    </td>
                    <td class="td-actions text-right">
                      <a href="{{ route('tutor.package.delete', $userPackage->id) }}">
                        <button type="button" rel="tooltip" title="Delete package" class="btn btn-primary btn-link btn-sm">
                          <i class="material-icons">delete</i>
                        </button>
                      </a>
                      <a href="" class="edit-package" data-id="{{$userPackage->id}}" data-name="{{$userPackage->package_name}}" data-description="{{$userPackage->description}}" data-fee="{{$userPackage->subscription_fee}}">
                        <button type="button" rel="tooltip" title="Edit package" class="btn btn-primary btn-link btn-sm">
                          <i class="material-icons">edit</i>
                        </button>
                      </a>
                    </td>
                  </tr>
                  @endforeach
                  @endisset
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Modal -->
    <div id="editModal" class="modal fade" role="dialog">
      <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Edit Package</h4>
          </div>
          <div class="modal-body">
            <form action="{{ route('tutor.package.update') }}" method="POST" accept-charset="UTF-8" enctype="multipart/form-data">
              @csrf
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <input id="edit-id" type="hidden" name="id" class="form-control" value="">
                  <label class="bmd-label-floating">Package Name</label>
                  <input id="edit-name" type="text" name="package_name" class="form-control" value="">
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label class="bmd-label-floating">Description</label>
                  <input id="edit-description" type="text" name="description" class="form-control" value="">
                </div>
              </div>
              {{-- <div class="col-md-6">
                <div class="form-group">
                  <label class="bmd-label-floating">Subcription Fee</label>
                  <input id="fee" type="number" name="subscription_fee" class="form-control" value="">
                </div>
              </div> --}}
              <div class="col-md-6">
                <div class="form-group">
                  <label class="bmd-label-floating">Batch</label>
                  <select id="batch_id" name="batch_id[]" multiple class="form-control">
                    @isset($userBatches)
                    @foreach($userBatches as $value)
                    <option value="{{$value->id}}">{{$value->batch_name}}</option>
                    @endforeach
                    @endisset
                  </select>
                
                </div>
              </div> 
            </div>
              <button type="submit" class="btn btn-primary pull-right">Submit</button>
          </form>

          </div>
          
        </div>

      </div>
    </div>

    {{-- @isset($user)
    <div class="row d-flex justify-content-center">
      <div class="col-lg-8">
        <div class="card">
          <div class="card-header card-header-primary">
            <h4 class="card-title">
              Delete this Tutor
            </h4>
          </div>
          <div class="card-body">
            <form action="{{ route('tutor.destroy', $user->id) }}" method="POST">
                @csrf
                @method('DELETE')
              <div class="row">
                <div class="col-md-12">
                  Do you really want to do this ? Make sure you are selected the right item. This action is irreversible.
                  All data associated with this item will be erased permanantly.
                </div>
              </div>
              <button type="submit" class="btn btn-primary pull-right">Delete</button>
              <div class="clearfix"></div>
            </form>
          </div>
        </div>
      </div>
    </div>
    @endisset --}}
  </div>
</div>
@endsection

@section('custom-scripts')
  <script type="text/javascript">

      $( document ).ready(function() {
        $( ".edit-package" ).on( "click", function(e) {
          e.preventDefault();

          $('#edit-id').val($(this).attr('data-id'));
          $('#edit-name').val($(this).attr('data-name'));
          $('#edit-description').val($(this).attr('data-description'));
          // $('#fee').val($(this).attr('data-fee'));

          $('#editModal').modal('show');
          });

      });
  </script>
@endsection

v2/resources/views/admin/tutor/index.blade.php
@extends('layouts.dashboard')

@section('content')
@include('partials.nav')
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header card-header-primary">
            <!-- <h4 class="card-title ">Users</h4>
            <p class="card-category"> Here is a subtitle for this table</p> -->
            <ul class="nav nav-tabs" data-tabs="tabs">
                        <li class="nav-item">
                          <a class="nav-link active" href="{{route('tutor.create')}}">
                            <i class="material-icons">supervisor_account</i> Add Guru
                            <div class="ripple-container"></div>
                          <div class="ripple-container"></div></a>
                        </li>
                      </ul>

          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table">
                <thead class=" text-primary">
                  <th>ID</th>
                  <th>Name</th>
                  <th>Email</th>
                  <th>Phone</th>
                  <th class="text-right">Action</th>
                </thead>
                <tbody>
                  @isset($users)
                  @foreach($users as $user)
                  <tr>
                    <td>{{$loop->index + 1}}</td>
                    <td>{{$user->name}}</td>
                    <td>{{$user->email}}</td>
                    <td>{{$user->phone_number}}</td>
                    <td class="td-actions text-right">
                      <a href="{{ route('tutor.edit', $user->id) }}">
                        <button type="button" rel="tooltip" title="Edit Guru" class="btn btn-primary btn-link btn-sm">
                          <i class="material-icons">edit</i>
                        </button>
                      </a>
                      <a href="{{ route('tutor.show', $user->id) }}">
                        <button type="button" rel="tooltip" title="View Profile" class="btn btn-primary btn-link btn-sm">
                          <i class="material-icons">assignment_ind</i>
                        </button>
                      </a>
                      <a href="{{ route('tutor.portfolio.create', $user->id) }}">
                        <button type="button" rel="tooltip" title="Manage Portfolio" class="btn btn-primary btn-link btn-sm">
                          <i class="material-icons">face</i>
                        </button>
                      </a>

                      <a href="{{ route('tutor.package.create', $user->id) }}">
                        <button type="button" rel="tooltip" title="Manage Package" class="btn btn-primary btn-link btn-sm">
                          <i class="material-icons">book</i>
                        </button>
                      </a>

                      <a href="{{ route('tutor.batch.create', $user->id) }}">
                        <button type="button" rel="tooltip" title="Manage Batch" class="btn btn-primary btn-link btn-sm">
                          <i class="material-icons">source</i>
                        </button>
                      </a>
                    </td>
                  </tr>
                  @endforeach
                  @endisset
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection