routes/web.php
<?php
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/test/page',function(){
    dd(phpinfo());
});
Route::get('/test/page/video','Admin\GeneralsettingController@createvideo');
Route::post('/admin/tutor/file','Admin\GeneralsettingController@uploadLargeFiles')->name('files.upload.large');

Route::post('/file-upload/profile', 'Admin\TutorController@storeProfileVideo')->name('profile.StoreVideo');
Route::post('/file-upload/{id}', 'Admin\TutorController@storePortFolioVideo')->name('portfolio.StoreVideo');
Route::post('/file-upload/package/{id}', 'Admin\TutorController@storePackageVideo')->name('package.StoreVideo');
Route::post('/file-upload/module/{id}', 'Admin\TutorController@storeModuleVideo')->name('module.StoreVideo');
Route::post('/file-upload/live/{id}', 'Admin\TutorController@storeLiveVideo')->name('live.StoreVideo');
  
Route::get('/', 'Auth\LoginController@showLoginForm')->name('welcome');
Route::get('/login1', 'Auth\LoginController@showLoginForm')->name('welcome');

Auth::routes();

Route::get('/home', 'Admin\AdminController@index')->name('admin.home');
Route::get('/terms-and-conditions', 'CommonController@terms')->name('common.terms');
Route::get('/privacy-policy', 'CommonController@policy')->name('common.policy');
Route::get('/get-batch-by-user', 'CommonController@getBatch')->name('common.getBatch');

//SuperAdmin Routes
Route::get('/admin', 'Admin\AdminController@index')->name('admin.home');
Route::get('/admin/help-desk', 'Admin\AdminController@helpDesk')->name('admin.helpdesk');
Route::resource('/admin/terms',  'Admin\TermsController')->except(['show']);
Route::resource('/admin/policy',  'Admin\PolicyController')->except(['show']);
Route::resource('/admin/user',  'Admin\UserController');

Route::middleware('auth')->group(function () {
Route::resource('/admin/tutor',  'Admin\TutorController');
 
// Route::get('/admin/tutor',  'Admin\TutorController@index')->name('tutor.index');
// Route::get('/admin/tutor/{id}',  'Admin\TutorController@show')->name('tutor.show');
// Route::get('/admin/tutor/create/{showNext}',  'Admin\TutorController@createProfile')->name('admin.tutor.create');
Route::get('/admin/tutor/edit/{id}/{showNext}',  'Admin\TutorController@edit')->name('admin.tutor.edit');
Route::post('/admin/tutor/update/{id}/{showNext}',  'Admin\TutorController@update')->name('admin.tutor.update');
Route::get('/admin/tutor/delete/{id}',  'Admin\TutorController@destroy')->name('admin.tutor.delete');

Route::resource('/admin/sessions',  'Admin\SessionsController')->except(['show']);
Route::resource('/admin/payment',  'Admin\PaymentController')->except(['show']);
//skills and category
Route::resource('/admin/category',  'Admin\CategoryController')->except(['show']); 
Route::get('/admin/category/delete/{id}',  'Admin\CategoryController@delete')->name('category.delete'); 

Route::resource('/admin/skill',  'Admin\SkillController')->except(['show']);
Route::get('/admin/skill/delete/{id}',  'Admin\SkillController@delete')->name('skill.delete');

Route::resource('/admin/banner',  'Admin\BannerController')->except(['show']);
Route::resource('/admin/subcategory',  'Admin\SubCategoryController')->except(['show']);



Route::resource('/admin/region',  'Admin\RegionController')->except(['show']);
Route::get('/admin/region/delete/{id}',  'Admin\RegionController@delete')->name('region.delete');
Route::resource('/admin/country',  'Admin\CountryController')->except(['show']);
Route::get('/admin/country/delete/{id}',  'Admin\CountryController@delete')->name('country.delete');

Route::resource('/admin/grade',  'Admin\GradeController')->except(['show']);
Route::resource('/admin/cmsfield',  'Admin\CmsFieldController')->except(['show']);
Route::get('/admin/get_subcategory',  'Admin\SubCategoryController@getSubCategory')->name('admin.getsubcategory');
Route::get('/admin/get_adminsubcategory',  'Admin\SubCategoryController@getAdminSubCategory')->name('admin.getadminsubcategory');
Route::get('/admin/profile', 'Admin\AdminController@profile')->name('admin.profile');
Route::get('/admin/send', 'Admin\EmailController@send')->name('email.send');
Route::post('/admin/profile/update', 'Admin\AdminController@profileUpdate')->name('admin.profile.update');
Route::resource('/admin/admin-banner',  'Admin\BannerController')->except(['show']);

Route::resource('/admin/generalsetting',  'Admin\GeneralsettingController')->except(['show']);
Route::get('/admin/generalsetting/view-currency',  'Admin\GeneralsettingController@viewCurrency')->name('admin.settings.viewCurrency');
Route::post('/admin/generalsetting/view-currency/store',  'Admin\GeneralsettingController@currencyStore')->name('admin.settings.currencyStore');
Route::post('/admin/generalsetting/view-currency/update',  'Admin\GeneralsettingController@currencyUpdate')->name('admin.settings.currencyUpdate');

Route::get('/admin/generalsetting/view-currency/create',  'Admin\GeneralsettingController@createCurrency')->name('admin.currency_settings.createCurrency');
Route::post('/admin/generalsetting/storeCurrency',  'Admin\GeneralsettingController@storeCurrency')->name('admin.currency_settings.storeCurrency');
Route::get('/admin/generalsetting/view-currency/{id}/edit',  'Admin\GeneralsettingController@editCurrency')->name('admin.currency_settings.editCurrency');
Route::post('/admin/generalsetting/updateCurrency/{id}',  'Admin\GeneralsettingController@updateCurrency')->name('admin.currency_settings.updateCurrency');
Route::get('/admin/generalsetting/deleteCurrency/{id}',  'Admin\GeneralsettingController@deleteCurrency')->name('admin.currency_settings.deleteCurrency');
Route::get('/admin/generalsetting/tier',  'Admin\GeneralsettingController@get_tier')->name('admin.tier.index');
Route::get('/admin/generalsetting/tier/create',  'Admin\GeneralsettingController@createTier')->name('admin.tier.create');
Route::post('/admin/generalsetting/tier',  'Admin\GeneralsettingController@storeTier')->name('admin.tier.storeTier');
Route::get('/admin/generalsetting/tier/{id}/edit', 'Admin\GeneralsettingController@editTier')->name('admin.tier.edit');
Route::post('/admin/generalsetting/tier/update/{id}',  'Admin\GeneralsettingController@updateTier')->name('admin.tier.update');
Route::get('/admin/generalsetting/tier/delete/{id}',  'Admin\GeneralsettingController@deleteTier')->name('admin.tier.delete');
Route::get('/admin/generalsetting/tier/currencyRange',  'Admin\GeneralsettingController@view_currency_range')->name('admin.tier.currency_range.index');
Route::get('/admin/generalsetting/tier/currencyRange/create',  'Admin\GeneralsettingController@createTierCurrency')->name('admin.tier.currency_range.create');
Route::post('/admin/generalsetting/tier/currencyRange/store',  'Admin\GeneralsettingController@StoreTierCurrency')->name('admin.tier.currency_range.store');
Route::get('/admin/generalsetting/tier/currencyRange/{id}/edit',  'Admin\GeneralsettingController@editTierCurrency')->name('admin.tier.currency_range.edit');
Route::post('/admin/generalsetting/tier/currencyRange/update/{id}',  'Admin\GeneralsettingController@updateTierCurrency')->name('admin.tier.currency_range.update');
Route::get('/admin/generalsetting/tier/currencyRange/delete/{id}',  'Admin\GeneralsettingController@deleteTierCurrency')->name('admin.tier.currency_range.delete');


Route::resource('/admin/recentbooking',  'Admin\RecentbookingController')->except(['show']);
Route::get('/get_admin_payment',  'Admin\PaymentController@get_admin_payment')->name('get_admin_payment');
Route::get('/admin/refund-payment/{id}', 'Admin\PaymentController@refundPayment')->name('buddy.refund.payment');
Route::get('/get_admin_recentbooking',  'Admin\RecentbookingController@get_admin_recentbooking')->name('get_admin_recentbooking');

Route::get('/admin/tutor/portfolio/create/{id}/{showNext}', 'Admin\TutorController@createPortfolio')->name('tutor.portfolio.create');
Route::post('/admin/tutor/portfolio/{showNext}', 'Admin\TutorController@storePortfolio')->name('tutor.portfolio.store');
Route::get('/admin/tutor/portfolio/{id}/edit', 'Admin\TutorController@editPortfolio')->name('tutor.portfolio.edit');
Route::post('/admin/tutor/portfolio/update/{id}', 'Admin\TutorController@updatePortfolio')->name('tutor.portfolio.update');
Route::get('/admin/tutor/portfolio/delete/{id}', 'Admin\TutorController@deletePortfolio')->name('tutor.portfolio.delete');

Route::get('/admin/tutor/package/index/{id}', 'Admin\TutorController@viewPackage')->name('tutor.package.view');
Route::get('/admin/tutor/package/view/{id}', 'Admin\TutorController@showPackage')->name('tutor.package.show');
Route::get('/admin/tutor/package/create/{id}/{showNext}', 'Admin\TutorController@createPackage')->name('tutor.package.create');
Route::get('/admin/tutor/package/{id}/edit', 'Admin\TutorController@editPackage')->name('tutor.package.edit');
Route::post('/admin/tutor/package/{showNext}', 'Admin\TutorController@storePackage')->name('tutor.package.store');
Route::post('/admin/tutor/package/update/{id}', 'Admin\TutorController@updatePackage')->name('tutor.package.update');
Route::get('/admin/tutor/package/delete/{id}', 'Admin\TutorController@deletePackage')->name('tutor.package.delete');

Route::get('/admin/tutor/module/view/{id}', 'Admin\TutorController@showModule')->name('tutor.module.show');
Route::get('/admin/tutor/module/index/{id}', 'Admin\TutorController@viewModule')->name('tutor.module.view');
Route::get('/admin/tutor/module/create/{id}/{showNext}', 'Admin\TutorController@createModule')->name('tutor.module.create');
Route::get('/admin/tutor/module/{id}/edit', 'Admin\TutorController@editModule')->name('tutor.module.edit');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use MohamedGaber\SanctumRefreshToken\Traits\HasApiTokens;

class User extends Authenticatable
{
    use Notifiable, HasApiTokens;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name','commision','description','email','dob', 'slug','password','role','phone_number','location','token','otp_verification','profile_image','image_file_name'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    protected $dates = ['dob'];

    //User.php
    public function payments()
    {
        return $this->hasMany(\App\Payment::class);
    }

    // public function country()
    // {
    //     return $this->hasOne('\App\Country', 'id','location');
    // }

    public function student_detail()
    {
        return $this->hasOne(\App\StudentDetail::class);
    }

    public function tutor_detail()
    {
        // return $this->hasOne(\App\TutorDetail::class);
        return $this->belongsTo('\App\TutorDetail', 'id', 'user_id');
    }

    public function session_detail()
    {
        return $this->hasMany(\App\Sessions::class);
    }
    public function country()
    {
        return $this->belongsTo('\App\Country', 'location', 'id');
    }
    public function userskill()
    {
        return $this->hasOne('App\Skill', 'id','skills');
    }
  
    public function user_category()
    {
        return $this->hasOne('App\Category', 'id','category');
    }
    public function student_category()
    {
        return $this->hasOne('App\Category', 'id','grade');
    }
    public function user_sub_category()
    {
        return $this->hasOne('App\SubCategory', 'id','sub_category');
    }
}

resources/views/admin/user/create_edit.blade.php
@php
    $formAction = isset($user) ? route('user.update', $user->id) : route('user.store');
    $issetUser = isset($user) ? 1 : 0;
        $options=$countries;
    $grades=$grade;

@endphp
@extends('layouts.dashboard')

@section('content')
@include('partials.nav')
<div class="content">
  <div class="container-fluid">
    <div class="row d-flex justify-content-center">
      <div class="col-lg-8">
        <div class="card">
          <div class="card-header card-header-primary">
            <h4 class="card-title">
              @isset($user)
                  Edit Details
              @else
                  Add New User
              @endisset
            </h4>
            <p class="card-category">Complete your profile</p>
          </div>
          <div class="card-body">
            <form action="{{ $formAction }}" method="POST" accept-charset="UTF-8" enctype="multipart/form-data">
              @isset($user) @method('PUT') @endisset
              @csrf
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label class="bmd-label-floating">Name</label>
                    <input id="name" type="text" name="name" class="form-control"
                        value="{{ old('name') ?? ($issetUser ? $user->name : '')  }}">
                    @error ('name')
                        <p class="text-danger">{{ $message }}</p>
                    @enderror
                  </div>
                </div>
                  <div class="col-md-6">
                      <div class="form-group">
                          <label class="bmd-label-floating">Dob</label>
                          <input id="dob" type="date" name="dob" class="form-control"
                                 value="{{ old('dob') ?? ($issetUser ? substr($user->dob,0,-9) : '')  }}">
                          @error ('dob')
                          <p class="text-danger">{{ $message }}</p>
                          @enderror
                      </div>
                  </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label class="bmd-label-floating">Email</label>
                    <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') ?? ($issetUser ? $user->email : '')  }}" required autocomplete="email">

                    @error('email')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label class="bmd-label-floating">Phone Number</label>
                    <input id="phone_number" type="number" class="form-control @error('phone_number') is-invalid @enderror" name="phone_number" value="{{ old('phone_number') ?? ($issetUser ? $user->phone_number : '')  }}" required autocomplete="phone_number">

                    @error('phone_number')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label class="bmd-label-floating">Password</label>
                    <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" {{($issetUser) ? '' : 'required'}} autocomplete="new-password">

                    @error('password')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label class="bmd-label-floating">Confirm Password</label>
                    <input id="password-confirm" type="password" class="form-control" name="password_confirmation" {{($issetUser) ? '' : 'required'}} autocomplete="new-password">
                  </div>
                </div>
              </div>

              <!-- <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label class="bmd-label-floating">Parent Name</label>
                    <input id="parent_name" type="text" name="parent_name" class="form-control"
                           value="{{ old('parent_name') ?? ($issetUser ? $user->student_detail->parent_name : '')  }}">
                    @error ('parent_name')
                    <p class="text-danger">{{ $message }}</p>
                    @enderror
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label class="bmd-label-floating">Parent Email</label>
                    <input id="parent_email" type="text" name="parent_email" class="form-control"
                           value="{{ old('parent_email') ?? ($issetUser ? $user->student_detail->parent_email : '')  }}">
                    @error ('parent_email')
                    <p class="text-danger">{{ $message }}</p>
                    @enderror
                  </div>
                </div>
              </div> -->

              <div class="row">
                <!-- <div class="col-md-6">
                  <div class="form-group">
                    <label class="bmd-label-floating">Parent Mobile</label>
                    <input id="parent_mobile" type="text" name="parent_mobile" class="form-control"
                           value="{{ old('parent_mobile') ?? ($issetUser ? $user->student_detail->parent_mobile : '')  }}">
                    @error ('parent_mobile')
                    <p class="text-danger">{{ $message }}</p>
                    @enderror
                  </div>
                </div> -->
                  <div class="col-md-12">
                      <div class="form-group">
                          <label class="bmd-label-floating">Country</label>
                          <select name="location" id="location" class="form-control @error('location') is-invalid @enderror">
                              <option value=""></option>
                              @foreach ($options as $key => $value)
                                  <option value="{{ $value['id'] }}" {{($issetUser && $user->location == $value['id']) ? 'selected' : ''}}>{{ $value['country_name'] }}</option>
                              @endforeach
                          </select>
                          @error('location')
                          <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                          @enderror
                      </div>
                  </div>
              </div>

              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label class="bmd-label-floating">Skills</label>
                      <select name="skills" id="skills" class="form-control @error('skills') is-invalid @enderror">
                          <option value=""></option>
                          @foreach ($skills as $key => $value)
                              <option value="{{ $value['id'] }}" {{($issetUser && $user->student_detail->skills == $value['id']) ? 'selected' : ''}} >{{ $value['skill_name'] }}</option>
                          @endforeach
                      </select>
                  </div>
                </div>
                  <div class="col-md-6">
                      <div class="form-group">
                          <label class="bmd-label-floating">Grade</label>
                          <select name="grade" id="grade" class="form-control @error('grade') is-invalid @enderror">
                              <option value=""></option>
                              @foreach ($grades as $key => $value)
                                  <option value="{{ $value['id'] }}" {{($issetUser && $user->student_detail->grade == $value['id']) ? 'selected' : ''}}>{{ $value['grade_name'] }}</option>
                              @endforeach
                          </select>
                      </div>
                  </div>

              </div>


              <button type="submit" class="btn btn-primary pull-right">Submit</button>
              <div class="clearfix"></div>
            </form>
          </div>
        </div>
      </div>
    </div>
    @isset($user)
    <div class="row d-flex justify-content-center">
      <div class="col-lg-8">
        <div class="card">
          <div class="card-header card-header-primary">
            <h4 class="card-title">
              Delete this User
            </h4>
          </div>
          <div class="card-body">
            <form action="{{ route('user.destroy', $user->id) }}" method="POST">
                @csrf
                @method('DELETE')
              <div class="row">
                <div class="col-md-12">
                  Do you really want to do this ? Make sure you are selected the right item. This action is irreversible.
                  All data associated with this item will be erased permanantly.
                </div>
              </div>
              <button type="submit" class="btn btn-primary pull-right">Delete</button>
              <div class="clearfix"></div>
            </form>
          </div>
        </div>
      </div>
    </div>
    @endisset
  </div>
</div>
@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.dashboard')

@section('content')
@include('partials.nav')
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header card-header-info">
            <!-- <h4 class="card-title ">Users</h4>
            <p class="card-category"> Here is a subtitle for this table</p> -->
            <ul class="nav nav-tabs" data-tabs="tabs">
                        <li class="nav-item">
                          <a class="nav-link active" href="{{route('user.create')}}">
                            <i class="material-icons">supervisor_account</i> Add
                            <div class="ripple-container"></div>
                          <div class="ripple-container"></div></a>
                        </li>
                      </ul>

          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table">
                <thead>
                  <th>ID</th>
                  <th>Name</th>
                  <th>Email</th>
                  <th>Phone</th>
                  <th class="text-center">Action</th>
                </thead>
                <tbody>
                  @isset($users)
                  @foreach($users as $user)
                  <tr>
                    <td>{{$loop->index + 1}}</td>
                    <td>{{$user->name}}</td>
                    <td>{{$user->email}}</td>
                    <td>{{$user->phone_number}}</td>
                    <td class="td-actions text-right">
                      <a href="{{ route('user.edit', $user->id) }}">
                        <button type="button" rel="tooltip" title="Edit Student" class="btn btn-primary btn-link btn-sm">
                          <i class="material-icons">edit</i>
                        </button>
                      </a>
                      <a href="{{ route('user.show', $user->id) }}">
                        <button type="button" rel="tooltip" title="View Profile" class="btn btn-primary btn-link btn-sm">
                          <i class="material-icons">assignment_ind</i>
                        </button>
                      </a>
                    </td>
                  </tr>
                  @endforeach
                  @endisset
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/admin/user/show.blade.php
@extends('layouts.dashboard')

@section('content')
    @include('partials.nav')
    <div class="content">
        <div class="container-fluid">
            <div class="row d-flex justify-content-center">
                <div class="col-lg-8">
                    <div class="card">
                        <div class="card-header card-header-primary">
                            <h4 class="card-title">
                                Buddy Profile
                            </h4>
                            <p class="card-category">Buddy profile details</p>
                        </div>
                        <div class="card-body">

                            <div class="row justify-content-md-center">
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <img src="{{ asset($user->profile_image) }}" class="img-thumbnail" />
                                    </div>
                                </div>
                            </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="bmd-label-floating">Name</label><br>
                                            {{ $user->name }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="bmd-label-floating">DOB</label><br>
                                            {{ $user->dob->format('d/m/Y') }}
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="bmd-label-floating">Email</label><br>
                                            {{ $user->email }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="bmd-label-floating">Phone Number</label><br>
                                            {{ $user->phone_number }}
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="bmd-label-floating">Parent Name</label><br>
                                            {{ $user->student_detail->parent_name }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="bmd-label-floating">Parent Email</label><br>
                                            {{ $user->student_detail->parent_email }}
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="bmd-label-floating">Parent Mobile</label><br>
                                            {{ $user->student_detail->parent_mobile }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="bmd-label-floating">Country</label><br>
                                            {{ $user->country->country_name }}
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="bmd-label-floating">Skills</label><br>
                                            
                                            {{ $user->student_detail->getSkill->skill_name }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="bmd-label-floating">Grade</label><br>
                                            {{ $user->student_detail->getGrade->grade_name }}
                                        </div>
                                    </div>

                                </div>
                                

                                <div class="clearfix"></div>
                            
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
@endsection